//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klient
    {
        public int Customer_ID { get; set; }
        public string FistName { get; set; }
        public string FamilyName { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
    }
}
